sudo: false
language: python
python:
  - "3.5"
services:
    - postgresql
addons:
  postgresql: "9.3"
before_script:
    - psql -c 'create database simplex_db;' -U postgres
install:
  - pip install tox coveralls
env:
  - TOX_ENV=flake8
  - TOX_ENV=docs
  - TOX_ENV=tests
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
