sudo: false
language: python
python:
  - "3.5"
addons:
  postgresql: "9.5"
before_script:
  - createdb simplex_db
install:
  - pip install tox coveralls
env:
  - TOX_ENV=flake8
  - TOX_ENV=docs
  - TOX_ENV=tests
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
