elasticsearch:
  image: elasticsearch:2.1.1
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./config:/usr/share/elasticsearch/config
# redis container
redis:
  image: redis:3.0.7
rabbitmq:
  image: "rabbitmq:3.6.0"
  hostname: "rmq"
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASSWORD=guest
db:
  image: postgres:9.4
web:
  #image: 568754562511.dkr.ecr.us-east-1.amazonaws.com/mrfantastic:latest
  build: .
  ports:
    - "8000:8000"
  volumes:
    - ~/datasets/:/app/data
    - .:/app
  links:
    - db
    - elasticsearch
    - rabbitmq
    - redis
  environment:
    - PYTHONDONTWRITEBYTECODE=1
    - DATABASE_URL=postgres://postgres@db/postgres
    - DEBUG=True
    - ALLOWED_HOSTS=localhost,127.0.0.1,
    - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
    - DSN=https://762be8db9221413eb6079a4f0e2feb2e:225a22a4224c4fdcb2a8a12c2b6e5a16@app.getsentry.com/66980
    - NEW_RELIC_LICENSE_KEY=001b141e3345317e86299f2337a9c8cd1718d348
    - NEW_RELIC_APP_NAME=mrfantastic
  command:
    ./bin/run-dev.sh
# container with redis worker
worker:
  #image: 568754562511.dkr.ecr.us-east-1.amazonaws.com/mrfantastic:latest 
  build: .
  volumes:
    - .:/app
  links:
    - db
    - rabbitmq
    - redis
  command: ./bin/run-celery.sh
  environment:
    - PYTHONDONTWRITEBYTECODE=1
    - DATABASE_URL=postgres://postgres@db/postgres
    - DEBUG=True
    - ALLOWED_HOSTS=localhost,127.0.0.1,
    - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
    - DSN=https://762be8db9221413eb6079a4f0e2feb2e:225a22a4224c4fdcb2a8a12c2b6e5a16@app.getsentry.com/66980
    - NEW_RELIC_LICENSE_KEY=001b141e3345317e86299f2337a9c8cd1718d348
    - NEW_RELIC_APP_NAME=mrfantastic
