db:
  image: postgres:9.4
web:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/app
  links:
    - db
  environment:
    - PYTHONDONTWRITEBYTECODE=1
    - DATABASE_URL=postgres://postgres@db/postgres
    - DEBUG=True
    - ALLOWED_HOSTS=localhost,127.0.0.1,
    - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
    - DSN='https://762be8db9221413eb6079a4f0e2feb2e:225a22a4224c4fdcb2a8a12c2b6e5a16@app.getsentry.com/66980'
  command:
    ./bin/run-dev.sh
