# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('address', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.TextField()),
                ('zipcode', models.CharField(max_length=10)),
                ('mail_state', models.TextField()),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'mailing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prints',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('file_directory', models.TextField()),
                ('file', models.TextField()),
                ('image_file', models.TextField()),
                ('thumbnail_file', models.TextField()),
                ('print_file', models.TextField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('tags', models.TextField()),
            ],
            options={
                'db_table': 'prints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsMailing',
            fields=[
                ('email', models.TextField()),
                ('mailing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts_mailing',
            },
        ),
        migrations.CreateModel(
            name='AccountsPrints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('print_field', models.BigIntegerField(blank=True, db_column='print', null=True)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts_prints',
            },
        ),
    ]
