# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('city', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('address', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.TextField()),
                ('zipcode', models.CharField(max_length=10)),
                ('mail_state', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('mailing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplex.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('file_path', models.TextField()),
                ('image_file', models.TextField()),
                ('thumbnail_file', models.TextField()),
                ('print_file', models.TextField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('confidence', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='AccountsMailing',
        ),
        migrations.DeleteModel(
            name='AccountsPrints',
        ),
        migrations.AddField(
            model_name='print',
            name='tags',
            field=models.ManyToManyField(to='simplex.Tag'),
        ),
        migrations.AddField(
            model_name='job',
            name='to_print',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplex.Print'),
        ),
        migrations.AddField(
            model_name='comment',
            name='print_field',
            field=models.ForeignKey(db_column='print', on_delete=django.db.models.deletion.DO_NOTHING, to='simplex.Print'),
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.ManyToManyField(to='simplex.Address'),
        ),
        migrations.AddField(
            model_name='account',
            name='comments',
            field=models.ManyToManyField(to='simplex.Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='prints',
            field=models.ManyToManyField(to='simplex.Print'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
