# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplex', '0002_auto_20160218_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('mailing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplex.Account')),
                ('to_print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplex.Print')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='job',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='to_print',
        ),
        migrations.AddField(
            model_name='job',
            name='argument',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='result',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('finished', 'finished'), ('failed', 'failed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('fibonacci', 'fibonacci'), ('power', 'power')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
