# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplex', '0008_auto_20160223_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='argument',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.IntegerField(null=True),
        ),
    ]
