# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplex', '0009_auto_20160223_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='print_field',
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 24, 19, 26, 39, 394344, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='print',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 24, 19, 26, 44, 966637, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
