# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplex', '0010_auto_20160224_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 0, 39, 16, 176273, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 0, 39, 16, 172973, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 0, 39, 16, 179849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='print',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 0, 39, 16, 174484, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='print',
            name='tags',
        ),
        migrations.AddField(
            model_name='print',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simplex.Tag'),
        ),
    ]
