# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplex', '0011_auto_20160227_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 1, 22, 55, 47, 602883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 1, 22, 55, 47, 595723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 1, 22, 55, 47, 610380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='print',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 1, 22, 55, 47, 597468, tzinfo=utc)),
        ),
    ]
