# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplex', '0012_auto_20160301_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='account',
            name='prints',
        ),
        migrations.AddField(
            model_name='account',
            name='addresses',
            field=models.ManyToManyField(to='simplex.Address'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simplex.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='print',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simplex.Account'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 0, 43, 35, 901085, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 0, 43, 35, 900500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('fibonacci', 'fibonacci'), ('power', 'power'), ('convert_ply_pcd', 'convert_ply_pcd'), ('generate_tags', 'generate_tags')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 0, 43, 35, 905848, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='print',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 0, 43, 35, 903365, tzinfo=utc)),
        ),
    ]
