# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplex', '0014_auto_20160418_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 0, 58, 10, 197312, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 0, 58, 10, 196621, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 0, 58, 10, 201494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='print',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 0, 58, 10, 199197, tzinfo=utc)),
        ),
    ]
