# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplex', '0015_auto_20160418_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='argument',
        ),
        migrations.AddField(
            model_name='job',
            name='input_argument',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='output_argument',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 19, 59, 20, 330731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 19, 59, 20, 330139, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('convert_ply_pcd', 'convert_ply_pcd'), ('generate_tags', 'generate_tags'), ('pcd_to_vfh_histogram', 'pcd_to_vfh_histogram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 19, 59, 20, 335548, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='print',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 19, 59, 20, 332460, tzinfo=utc)),
        ),
    ]
