# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-14 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplex', '0020_auto_20160814_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 22, 5, 45, 827936, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 22, 5, 45, 827082, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 22, 5, 45, 831914, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='print',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 22, 5, 45, 829610, tzinfo=utc)),
        ),
    ]
